package agilie.example.swipe2delete

fun prepareContactList(count: Int): MutableList<User> {
    val result = ArrayList<User>(count)
    result.add(User(0, "Daniel Weaver", "Nauru"))
    result.add(User(1, "Vance Stanton", "Russian Federation"))
    result.add(User(2, "Nasim Ingram", "United Arab Emirates"))
    result.add(User(3, "Duncan Grimes", "Libya"))
    result.add(User(4, "Logan Mcgee","Palau"))
    result.add(User(5, "Berk Kemp", "Albania"))
    result.add(User(6, "Solomon Warren", "Viet Nam"))
    result.add(User(7, "Quentin Maldonado", "Aruba"))
    result.add(User(8, "Isaac Garza", "Malta"))
    result.add(User(9, "Tobias Workman", "Mali"))
    result.add(User(10, "Channing Frederick", "Congo (Brazzaville)"))
    result.add(User(11, "Phelan Booker", "Cocos (Keeling) Islands"))
    result.add(User(12, "Amery Lewis", "San Marino"))
    result.add(User(13, "Valentine Nolan", "Turks and Caicos Islands"))
    result.add(User(14, "Jamal Walls", "Christmas Island"))
    result.add(User(15, "Jack Noel", "Nicaragua"))
    result.add(User(16, "Alvin Peterson", "Malta"))
    result.add(User(17, "Brody Gilmore", "Bonaire, Sint Eustatius and Saba"))
    result.add(User(18, "Arden Rich", "Uzbekistan"))
    result.add(User(19, "Andrew Bauer", "Indonesia"))
    result.add(User(20, "Erich Bernard", "India"))
    result.add(User(21, "George Hayes", "Georgia"))
    result.add(User(22, "Carlos Slater", "France"))
    result.add(User(23, "Talon Harrington", "Congo (Brazzaville)"))
    result.add(User(24, "Silas Navarro", "French Southern Territories"))
    result.add(User(25, "Ryan Drake", "Maldives"))
    result.add(User(26, "Jesse Rojas", "Sao Tome and Principe"))
    result.add(User(27, "Aladdin Blankenship", "Tunisia"))
    result.add(User(28, "Raja Valdez", "Holy See (Vatican City State)"))
    result.add(User(29, "Chadwick Watkins", "Dominican Republic"))
    result.add(User(30, "Chaney Best", "French Polynesia"))
    return result
}